### ISSUE TITLE
error at req: connect

### ISSUE THREAD

**Issue by holden777** [tonesto7/homebridge-smartthings#101]
I am having a hard time getting homebridge to work after a lot of errors I worked my way through I get this one
my config.json is at the bottom
Thanks for any help guys!

pi@raspberrypi:~/.homebridge $ homebridge
**\* WARNING **\* The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs
**\* WARNING **\* The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister
[10/9/2016, 2:50:32 AM] Loaded plugin: homebridge-smartthings
[10/9/2016, 2:50:32 AM] Registering platform 'homebridge-smartthings.SmartThings'
[10/9/2016, 2:50:32 AM] ---
[10/9/2016, 2:50:32 AM] Loaded config.json with 0 accessories and 1 platforms.
[10/9/2016, 2:50:32 AM] ---
[10/9/2016, 2:50:32 AM] Loading 1 platforms...
[10/9/2016, 2:50:32 AM] [SmartThingsHolden] Initializing homebridge-smartthings.SmartThings platform...
[10/9/2016, 2:50:32 AM] [SmartThingsHolden] Fetching Smart Things devices.
error at req:  connect EINVAL 0.0.1.187:443 - Local (0.0.0.0:0)
[10/9/2016, 2:50:32 AM] [SmartThingsHolden] Invalid Response from API call
[10/9/2016, 2:50:32 AM] [SmartThingsHolden] Unknown Capabilities: []
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

```
┌────────────┐
│ 031-45-154 │
└────────────┘
```

[10/9/2016, 2:50:32 AM] Homebridge is running on port 51826.
error at req:  connect EINVAL 0.0.1.187:443 - Local (0.0.0.0:0)
error at req:  connect EINVAL 0.0.1.187:443 - Local (0.0.0.0:0)
error at req:  connect EINVAL 0.0.1.187:443 - Local (0.0.0.0:0)
error at req:  connect EINVAL 0.0.1.187:443 - Local (0.0.0.0:0)
error at req:  connect EINVAL 0.0.1.187:443 - Local (0.0.0.0:0)
error at req:  connect EINVAL 0.0.1.187:443 - Local (0.0.0.0:0)
error at req:  connect EINVAL 0.0.1.187:443 - Local (0.0.0.0:0)
error at req:  connect EINVAL 0.0.1.187:443 - Local (0.0.0.0:0)
error at req:  connect EINVAL 0.0.1.187:443 - Local (0.0.0.0:0)
error at req:  connect EINVAL 0.0.1.187:443 - Local (0.0.0.0:0)

```
"bridge": {
    "name": "Homebridge",
    "username": "BC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
},
```

   "description": "JSON API",
   "platforms": [{

```
    "platform": "homebridge-smartthings.SmartThings",
    "name": "SmartThingsHolden",
    "app_url": "graph.na02-useast1.api.smartthings.com:443/api/smartapps/installations/",
    "app_id": "XXX-XXX",
    "access_token": "XXX-XXX",
    "polling_seconds": 600,
    "update_seconds": 1
```

  }]
}

**Comment by pdlove** [comment]
Let me know if this is working with the latest updates. I really think your app_url is incorrect.
