### ISSUE TITLE
Access to run routines ?

### ISSUE THREAD

**Issue by sebastienb** [tonesto7/homebridge-smartthings#102]
Is there anyway to allow the use of ST routines with this plugin ?

**Comment by alisdairjsmyth** [comment]
No - at least I don't think so. It allows ST devices to be controlled using the features and capabilities of HomeKit. HomeKit includes a feature called Scenes - scenes contain both accessories and actions for those accessories - and ST devices integrated into HomeKit through Homebridge and this plugin can be included in scenes.

**Comment by pdlove** [comment]
You could create a Virtual Momentary switch and tie the routine to trigger when that switch happens.
The momentary switch would then appear to HomeKit as a switch.

**Comment by ajvwhite** [comment]
You may want to look at:

https://www.npmjs.com/package/homebridge-smartthings-routine-triggers

Which will achieve what's being asked here.

Admittedly would be quite nice if it was built in to this?

**Comment by sebastienb** [comment]
Thank you I will give it a try
