### ISSUE TITLE
GE Fan Control shows as dimmable light in HomeKit

### ISSUE THREAD

**Issue by travismmorgan** [tonesto7/homebridge-smartthings#106]
I am using a GE Fan Control in the smart things app but when I access it via HomeKit, it shows up as a light and the type cannot be changed.

**Comment by mike-yesware** [comment]
I solved this by, in Smartthings, switching the device type to a user supplied GE fan controlled one. Look in the Smartthings community for instructions on how.

**Comment by pdlove** [comment]
What is the default device type that smartthings picks for the fan controller? I won't be able to install mine until sometime late next week.

**Comment by travismmorgan** [comment]
Dimmer Switch

**Comment by pdlove** [comment]
From my experimenting, the best solution for this is the user supplied GE Fan Device Type.
If that won't work for you for some reason then I can add an option where you specify certain device names to be treated as a fan instead of a dimmer.

**Comment by jansantanna** [comment]
i got the same problem, I guess there is no way to change it to a fan control,
