### ISSUE TITLE
Linear Garage Door Controller shows as two separate accessories

### ISSUE THREAD

**Issue by travismmorgan** [tonesto7/homebridge-smartthings#107]
Linear Garage Door Controller shows up as two separate accessories, a sensor and a switch. The switch does not function properly due to not knowing the status of the sensor. (i.e. stuck with "Closing..." status)

**Comment by mehak-bhatia** [comment]
I have the same issue with Aeon Labs Garage Door Controller. Garage door stuck at "Closing..." 
I have to restart Homebridge everytime I open/close my garage door via HomeKit.

**Comment by fireheadman** [comment]
I have the same thing showing up on mine, however it seems to make sense to me like this.   The switch being the operator and the sensor showing the status.  I just relabelled mine to be Garage Door Opener and the the other Garage Door Contact.

My schlage front door lock shows up in 2 pieces also (lock and the other a contact sensor)

**Comment by pdlove** [comment]
I need to get an easy way for y'all to get me the JSON for the detected devices so I can see if Smartthings is exposing how it is linked so I can also link it. I'll let you know later this weekend how to do it.
