### ISSUE TITLE
SmartThings Motion Sensor [Question]

### ISSUE THREAD

**Issue by greenygh0st** [tonesto7/homebridge-smartthings#110]
So I have everything up and running so far the only thing that Home/HomeKit can't see is my SmartThings motion sensors. 

I am assuming that is probably because HomeKit does not (as of yet) have a concept of motion sensors. Anyone else had any different experiences with this?

**Comment by 5t1tch** [comment]
My motion sensors work perfectly ,but my contact sensors show wrong status 95%f the time.
Sorry I can't be of any help ,but I can confirm they should work

**Comment by greenygh0st** [comment]
No worries. I will keep tinkering with it and if I can figure out what is causing this I will post it here. 

Even if I can't it all to work perfectly in HomeKit it's not the end of the world to me. In fact - I dare say the most amazing thing about Homebridge and this plugin is it essentially forces a system/framework by Apple and a system now controlled by Samsung to hold hands and just get along. It's just a matter of making sure that they don't step on each other. 😄

**Comment by Quiqui64** [comment]
Are you using a custom device handler?

**Comment by greenygh0st** [comment]
I don't recall I will have to take a look at it.

**Comment by Memodellocos** [comment]
In my case, setting the "direct_ip" value to the IP of my homebridge system instead of originally thinking it should be the IP of the Smarthings hub seemed to fix the motion sensor for me. It updates correctly within moments. It does show as two accessories in the iOS Home App.
