### ISSUE TITLE
See two devices for every device

### ISSUE THREAD

**Issue by mshollack** [tonesto7/homebridge-smartthings#113]
I see my smart things devices but I see two. One switch and one light. The switch works but the light device does nothing. Why duplicated items showing?

**Comment by am80l** [comment]
+1

**Comment by LupoLoopy** [comment]
+1 - affects Samsung SmartThings Outlets, Fibaro dimmers & Fibaro relays.

Example JSON for Fibaro relay, by example:

{"name":"Security Light","deviceid":"0214de78-fc5b-4aa4-b46d-077fe3df50a9","capabilities":{"Switch":1,"Polling":1,"Configuration":1,"Refresh":1,"Energy Meter":1,"Power Meter":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"poll":[],"configure":[],"refresh":[],"reset":[],"configureAfterSecure":[]},"attributes":{"switch":"off","energy":3.95,"power":0}}

**Comment by LupoLoopy** [comment]
SmartThings Outlet JSON:
{"name":"M-DAC","deviceid":"f2d7e765-b3aa-4fb9-be58-f1d6d3a1c736","capabilities":{"Switch":1,"Configuration":1,"Refresh":1,"Power Meter":1,"Sensor":1,"Actuator":1,"Health Check":1},"commands":{"on":[],"off":[],"configure":[],"refresh":[],"ping":[]},"attributes":{"switch":"on","power":17.8,"checkInterval":1260}}

**Comment by mattdevo1** [comment]
+1

**Comment by lucianf** [comment]
+1. Is this a bug or is it by design?

**Comment by pdlove** [comment]
I think it's a bug in the way the Power Meter works. With the new release of the HomeKit spec I may be able to overcome some of these issues. I've got a SmartThings Outlet coming so I can duplicate this as well.

**Comment by nberardi** [comment]
I added a pull request for light switches. The problem I found with the code is that it tires to break out devices by capabilities. However capabilities are shared between devices often times. 

https://github.com/pdlove/homebridge-smartthings/pull/185

**Comment by JangoBritt** [comment]
+1 here (for what it's worth)

I also found that my Z-Wave Lock has both a Tamper Sensor, and a Smoke Detector capability in Smartthings, so this shows up as three separate devices!

My Simulated Thermostat has a Temperature device, and a Thermostat device, whereas my tado HomeKit ones have one device with multiple capabilities.

Nest Protect has a CO device, and a Smoke Device.

These are all likely, as @nberardi  has mentioned, due to breaking out the devices by capabilities.

**Comment by pdlove** [comment]
there is actually a discussion right now about this on the HAP-NodeJS project. The way that the Home app displays Accessories is actually by service. I had previously been working on a newer version of this plugin that allows more control over how SmartThings devices are mapped to HomeKit services. With the latest updates to the Samsung Home WiFi, I can finally use the built in hub, so I should be able to progress with development.
