### ISSUE TITLE
App ID changes every time I reboot

### ISSUE THREAD

**Issue by DanielGalle** [tonesto7/homebridge-smartthings#117]
Hi,

couldn't find anything on the internet so I ask here :-)

My app id always changes (installed the plug in on Friday and had to change it three times already). What do I have to do to keep the ID static?

Thanks,
Daniel

**Comment by pdlove** [comment]
I haven't ever seen this as an issue. Are you installing the app through the "Simulation" function of the SmartThings webpage? If so, that's the issue as you should do it from the smartthings app.
