### ISSUE TITLE
Smartsense Multi Missing Capabilities

### ISSUE THREAD

**Issue by humac** [tonesto7/homebridge-smartthings#12]
The SmartSense multi just shows up with Temp, Contact and Battery.  

[SmartThings] Device Added - Group sensor, Name Basement Window 1, ID <ID>, JSON: {"name":"Basement Window 1","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Contact Sensor":1,"Three Axis":1,"Acceleration Sensor":1,"Signal Strength":1,"Sensor":1},"commands":{},"attributes":{"temperature":11,"battery":13,"contact":"closed","threeAxis":{"x":0,"y":1055,"z":10},"acceleration":"inactive","lqi":100,"rssi":-48}}

**Comment by pdlove** [comment]
Should acceleration be a MotionDetector type or something custom?

**Comment by humac** [comment]
I think the smart sense multi's show it at something more custom.  I think acceleration is treated like vibration so if it's moving it just state "active" and "inactive" when it is still.  It also uses it to display it's orientation like tilt etc. 

Here is a screenshot of the device in ST app:
![img_0377](https://cloud.githubusercontent.com/assets/9813864/12935729/0ff57d06-cf66-11e5-8cfc-fada0f970466.PNG)

**Comment by pdlove** [comment]
Do you know the range of the numbers on the Three Axis? I can't find that information in the Smartthings API.

**Comment by lobo5519** [comment]
I am also using this device as a tilt sensor for a garage door which just always shows closed in the Home app.
