### ISSUE TITLE
getaddrinfo ENOTFOUND graph-na02-useast1...

### ISSUE THREAD

**Issue by jack-hub** [tonesto7/homebridge-smartthings#120]
Thank you for this plugin. Much appreciated.

Just installed tonight. After a couple of hiccups with the JSON, it is up and running. After a while I started getting a ton of these errors:

 getaddrinfo ENOTFOUND graph-na02-useast1.api.smartthings.com graph-na02-useast1.api.smartthings.com:443

With one: [12/1/2016, 7:13:44 PM] [SmartThings] Invalid Response from API call

And just got this...
error at req:  connect ETIMEDOUT 52.21.73.17:443

But it did not crash and it is running/working...

**Comment by jack-hub** [comment]
Overnight it failed with ETIMEDOUT errors, and then an invalid api response that seemed to take the SmartThings off the bridge.

**Comment by spikenheimer** [comment]
interesting find i made this week- after having countless issues with the ENOTFOUND issue, i decided to nuke my setup and start over.  so i re-added my smartthings setup and realized that my old config.json did **not** have the `poling_seconds` or `update_seconds` settings for my smartthings platform and instead was just a copy / paste of the json from the JSON API webpage...  so i put those in and now i havent seen the ENOTFOUND error after 3 days of running.  i'll update if the issue returns.

**Comment by frakman1** [comment]
Can you include the lines of JSON  (polling_seconds, update_seconds) please?

**Comment by spikenheimer** [comment]
my current config.json has this:  (keeping in mind that the current version of homebridge is vastly different than the one that was reporting this error 2 years ago...)

```
			   "polling_seconds": "180",
			   "update_method": "direct",
```
