### ISSUE TITLE
Thermostat sets heat to Maximum when Home Tile selected

### ISSUE THREAD

**Issue by JangoBritt** [tonesto7/homebridge-smartthings#123]
So for some reason, my SmartThings thermostat, in HomeKit (Home and Eve) defaults to Heat to 38 degrees, as soon as you open the device/tile.

If you don't make any chances, it doesn't change the target temperature, but when you close the tile, the target then displays "Heating to 38"... which is needless to say, quite alarming. lol

**Comment by pdlove** [comment]
Is this still occurring after the latest IOS updates?

**Comment by JangoBritt** [comment]
Welcome back!

Unfortunately yes 😞 see the below photos

Also, coincidentally, I get an additional tile with Temperature sensor capability, when the thermostat displays the detected temperature too. Seems redundant

![img_0625](https://cloud.githubusercontent.com/assets/19468670/22390365/6d8a6fe8-e4e2-11e6-8837-494e3214b1c1.PNG)
![img_0626](https://cloud.githubusercontent.com/assets/19468670/22390366/6d91d206-e4e2-11e6-96cc-48f2504750ba.PNG)

**Comment by pdlove** [comment]
What is the device type your thermostat is using in Smartthings?

**Comment by JangoBritt** [comment]
It's the Tado (connect) heating thermostat DH

**Comment by iamadan** [comment]
For what it's worth (and I know this is old), I have the exact same problem with Nest Manager on Smartthings (latest version of NM -- 5.1).  It scared me to see my heat shoot to the top when it's already warm in the house.
