### ISSUE TITLE
Camera Capability

### ISSUE THREAD

**Issue by JangoBritt** [tonesto7/homebridge-smartthings#124]
Are there any plans to add Camera capability to the SmartThings plugin?

**Comment by JangoBritt** [comment]
I guess that's a no, then?

**Comment by Xtropy74** [comment]
I think this project is abandoned. Pdlove hasn't posted or updated in months

**Comment by pdlove** [comment]
I apologize for the delays seen. At this time I have no plans to add camera capability due to a lack of understanding at how it works. I will re-evaluated in the future and, if anyone else can do this, that would be awesome as well.
