### ISSUE TITLE
AccessDenied Error

### ISSUE THREAD

**Issue by tingu03** [tonesto7/homebridge-smartthings#128]
When I try to start HomeBridge I get this error:

Error received type AccessDenied - This request is not authorized by the specific access token
Unknown Capabilities: []

I've already changed the app_url to the new one as suggested in #87 and everything else matches in the config files. I would really appreciate some help!
P.S: I'm a newbie and don't know much:)

**Comment by pdlove** [comment]
How are you getting your app id and token?

**Comment by cali0028** [comment]
So I am setting up V2 of the hub today and getting the following as well. 

"[SmartThings] Error received type AccessDenied - This request is not authorized by the specified access token"

I've tried to change the link as well but no go. I did get the ID/token from the smartthings app. 

on the side note i did take the code and checked on json validator and getting an error :

"description": "JSON API",
	"platforms": [{  <-------Here
		"platform": "SmartThings",
		"name": "SmartThings",
		"app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
		"app_id": "xxx",
		"access_token": "xxx"

Thoughts?

**Comment by pdlove** [comment]
Either The ID or token or url is wrong... Normally.

**Comment by pdlove** [comment]
From the reame: 

"app_url", "app_id" and "access_token" Required
To get this information, open SmartThings on your phone, goto "Automation">"SmartApps">"JSON Complete API" and tap on Config
The app_url in the example may be different for you.

**Comment by jeffl78** [comment]
I'm having the same issue, am a noob also, and would really like to see Homebridge work.  At first I could see Homebridge in my iOS home app on my iPhone but it no longer shows up when i set up the home app after resetting the everything.  I've reset everything multiple times, each time trying something different after finding tips in other posts on this thread and the web in general.  I'm running a pi 3b and am starting to learn a bit about pi and am decent with computers.  Any assistance would be greatly appreciated.

**Comment by jeffl78** [comment]
I should mention a few other details.....I have uninstalled and reinstalled homebridge once so far after the initial instillation.  Otherwise I've been signing out and/or resetting all the apps, plus config file.  I've been using my pi headless by remoting in with my pc and copy and pasting the config info from my email to Raspberian Jessie's text editor and we're I edit before copying to nano.  Additionally, I have been deleting the JSON smart app and redoing the set up for it on IDE & the smartthings iOS app.  I have some extra SD cards and will install on a fresh card next and omit the step with the text editor, instead coping directly into nano from my gmail.

**Comment by anuragsimgeker** [comment]
In your browser go to account.smartthings.com and login. It will redirect to a different website. Change to "graph.api.smartthings.com" in the config file to whatever the website was. In my case it was "graph-na02-useast1.api.smartthings.com". No more error.

**Comment by anuragsimgeker** [comment]
Duplicate #188

**Comment by jeffl78** [comment]
I've tried this and it still doesn't work.  I've reformatted several times and set everything up from scratch with no luck.  I've started using the iOS homebridge app as an interface to make the set up process less tedious and don't think this has any effect.  If anyone can help I'd appreciate the advice.

**Comment by jeffl78** [comment]
I've tried this and it still doesn't work.  I've reformatted several times and set everything up from scratch with no luck.  I've started using the iOS homebridge app as an interface to make the set up process less tedious and don't think this has any effect.  Additionally, the specific error I'm now getting says: "Invalid response from API call", and on the following line it says "Unknown Capacities []".  The logs also indicated SmartThings fetches but returns with 0 accessories.  If anyone can help I'd appreciate the advice.  

Here is my JSON config before adding anything unnecessary.  It is valid and runs on the iOS homebridge app very stable:

{
  "accessories" : [

  ],
  "bridge" : {
    "username" : "CD:22:3D:E3:CE:60",
    "name" : "Homebridge",
    "pin" : "031-45-730",
    "port" : 51826
  },
  "platforms" : [
    {
      "app_id" : "23b0deab-51ca-4eae-b842-ed024b2dd4a1",
      "app_url" : "https:\/\/graph-na04-useast2.api.smartthings.com\/",
      "direct_ip" : "192.168.0.45",
      "api_seconds" : "30",
      "update_method" : "direct",
      "platform" : "homebridge-smartthings.SmartThings",
      "update_port" : "8000",
      "access_token" : "d20e0dc8-36e3-4c69-a096-5bcb766606d6",
      "polling_seconds" : "3600",
      "name" : "SmartThings"
    }
  ]
}
