### ISSUE TITLE
Zigbee Valve Device use Open/Close as Main capability

### ISSUE THREAD

**Issue by humac** [tonesto7/homebridge-smartthings#13]
When I add the zigbee valve device it shows battery first, and has an on/off called Power State.  Can we have the primary capability be Open/Close?

[SmartThings] Device Added - Group switch, Name Main Water Valve, ID <ID>, JSON: {"name":"Main Water Valve","deviceid":"<ID>","capabilities":{"Switch":1,"Battery":1,"Configuration":1,"Refresh":1,"Valve":1},"commands":{"on":[],"off":[],"configure":[],"refresh":[],"open":[],"close":[]},"attributes":{"switch":"on","battery":null,"contact":null}}

**Comment by pdlove** [comment]
I'm looking into what it would take to create a custom service for this.
