### ISSUE TITLE
Switch capability is superseded by Energy Meter capability

### ISSUE THREAD

**Issue by wipika** [tonesto7/homebridge-smartthings#130]
Hi all -- this is my first submission so bear with me as I am quite new to this.

I have successfully built and ran homebridge with SmartThings and nearly all devices are being recognized and working.

The only issue I have is with a particular device, the Aeon Labs Heavy Duty Energy Switch. This device is really a switch, with some additional functions such as energy consumption monitoring, temperature monitoring etc.

The problem is that homebridge-smartthings recognizes this as an Energy Meter (since it lists this capability in the device type handler) and _nothing else_. This is a switch, and homebridge-smartthings completely omits this (and all other) capability and sticks with the Energy Meter one.

If I simply comment out this capability ("Energy Meter", along with "Power Meter" and "Temperature Measurement") in the device handler, then homebridge-smartthings detects it properly as a switch.

[Here is the code used](https://raw.githubusercontent.com/jpansarasa/SmartThings/master/DeviceTypes/AeotecHDSS.groovy) in the device handler. Any ideas why this strange issue occurs? Help would be much appreciated!

**Comment by pdlove** [comment]
What app are you using? It looks like it should be picked up as a Switch, Temperature Sensor and an Energy Meter. This might has something to do with the Energy Meter being implemented using a custom Characteristic. It really looks like the Switch should be the one overriding everything else.

**Comment by wipika** [comment]
I'm using the native Home app in iOS. Is there a way to "force" the order of the capabilities in the code perhaps, so it gets detected as a Switch but doesn't lose the other capabilities in the meantime?

**Comment by pdlove** [comment]
@wipika I think I've found the issue. It looks like the Temperature Measurement is actually the overriding factor that prevents it from being found as a switch. I'll get this corrected tomorrow and uploaded to GitHub.

**Comment by wipika** [comment]
@pdlove Thanks for looking into this. I pulled the latest update, however it looks like the Energy Meter capability is still overriding all others. If I now disable only this capability (and _not_ Temp Measurement and Power Meter anymore), homebridge picks it up correctly as a switch.

Not a big issue tbh, so I'm hoping it at least provides some input for the project.
