### ISSUE TITLE
SmartThings Direct Connect listening on TCP6 only

### ISSUE THREAD

**Issue by intrepidsilence** [tonesto7/homebridge-smartthings#145]
I updated to the new version of homebridge and homebridge-smartthings and followed all instructions.  When I start homebridge now I see the "Direct Connect Is Listening On XXX.XXX.XXX>XXX:8000" but I never see the "SmartThings Hub Communication Established" message.  I have no firewall on the device.  When I check netstat -an I see it listening on port 8000 but only for IPV6.  Ideas?

**Comment by pdlove** [comment]
You can specify the IPV4 address to listen on in the config file. That might help.
What OS Are you using?

**Comment by intrepidsilence** [comment]
Unfortunately I tried that already. This is the raapbian os on a pi 3


Michael Spurlock  
michael.spurlock@greyspaces.net

**Comment by pdlove** [comment]
I'll do a little research tonight. It'll give me an excuse to get homebridge back on my pi 3.

**Comment by intrepidsilence** [comment]
Thanks!


Michael Spurlock  
michael.spurlock@greyspaces.net

**Comment by intrepidsilence** [comment]
I am wondering if this is what is happening:

http://unix.stackexchange.com/questions/237731/why-are-ipv4-tcp-connections-showing-as-tcp6

Even so, I went ahead and disabled ipv6 and now it shows listening on tcp 8000.  However, I never get the connection established message as your instructions indicate.  Everything seems to work with my SmartThings hub and items but the updating of the status is much more unstable than it used to be.


Michael Spurlock
michael.spurlock@greyspaces.net

On February 17, 2017 at 15:17:18, pdlove (notifications@github.com) wrote:

I'll do a little research tonight. It'll give me an excuse to get homebridge back on my pi 3.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pdlove/homebridge-smartthings","title":"pdlove/homebridge-smartthings","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pdlove/homebridge-smartthings"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pdlove in #145: I'll do a little research tonight. It'll give me an excuse to get homebridge back on my pi 3."}],"action":{"name":"View Issue","url":"https://github.com/pdlove/homebridge-smartthings/issues/145#issuecomment-280755424"}}}

**Comment by pdlove** [comment]
I did a clean install of Raspbian and Homebridge and it's working fine for me.
I have IPv4 only on my network... Without the connection established message the status doesn't update very regularly.
You could do a packet capture looking for data from your Hub's IP.
The easiest solution is to setup a free PubNub account and use that as the update_method.

**Comment by intrepidsilence** [comment]
Thanks for checking into this. I will try a fresh install as well.  


Michael Spurlock  
michael.spurlock@greyspaces.net

**Comment by intrepidsilence** [comment]
I have another question for you.  I was going to set up a new instance of Raspbian and configure home bridge again on that to test it on a new config but I cannot get home bridge installed again due to node.js errors due to Debian’s crazy treatment of node.  I have tried many things and not had any success.  I cannot remember how I did it the first time.  What did you have to do to get it installed?


Michael Spurlock
michael.spurlock@greyspaces.net

On February 20, 2017 at 13:08:31, pdlove (notifications@github.com) wrote:

I did a clean install of Raspbian and Homebridge and it's working fine for me.
I have IPv4 only on my network... Without the connection established message the status doesn't update very regularly.
You could do a packet capture looking for data from your Hub's IP.
The easiest solution is to setup a free PubNub account and use that as the update_method.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pdlove/homebridge-smartthings","title":"pdlove/homebridge-smartthings","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pdlove/homebridge-smartthings"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pdlove in #145: I did a clean install of Raspbian and Homebridge and it's working fine for me.\r\nI have IPv4 only on my network... Without the connection established message the status doesn't update very regularly.\r\nYou could do a packet capture looking for data from your Hub's IP.\r\nThe easiest solution is to setup a free PubNub account and use that as the update_method."}],"action":{"name":"View Issue","url":"https://github.com/pdlove/homebridge-smartthings/issues/145#issuecomment-281147093"}}}

**Comment by pdlove** [comment]
https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

**Comment by intrepidsilence** [comment]
One more dumb question for you...  

In the instructions for setting up PubNub it says to "scroll down" and enter the keys. I have gone to the logical location based upon the spot you should be in based on everything that comes before that command and I cannot find anywhere to place the PubNub keys. Can you please add some clarifying data?  

Thanks in advance!

**Comment by pdlove** [comment]
First, you may not need PubNub. If your hub and homebridge are on the same network then they should communicate with each other.
In the SmartApp on the screen where you pick the devices there is a section that says "Configure Pubnub"

**Comment by intrepidsilence** [comment]
Do you mean in "My Home" under the "Things" tab? If yes, then no I do not have that option.


Michael Spurlock  
michael.spurlock@greyspaces.net

**Comment by pdlove** [comment]
In the SmartHome app on the phone under Automation>SmartApps... click on the JSON application (Whatever you've called it) and look there.

**Comment by intrepidsilence** [comment]
Nope, nothing there about PubNub. Says version 0.4.1. Is that the latest?


Michael Spurlock  
michael.spurlock@greyspaces.net

**Comment by intrepidsilence** [comment]
Nothing about Pubnub in that location or anywhere else that I can find.

**Comment by sra** [comment]
This might be related to my issue. I'm using this in a docker container on the RPI3 and there are several network interfaces. It is random which one gets returned first that matches the rules. I think there should be a way to pin the listen to a particular network interface. In my case it needs to be "wlan0".

This hit and miss on getting the "right" interface first makes the direct connect not initialize properly some of the time. SmartThings support contacted me about it again this weekend.

Maybe an option to notice an environment variable with the name of the interface to use?

**Comment by pdlove** [comment]
@sra The listener should happen on every interface. There's a configuration option you can set to declare the IP address the hub should communicate on.
