### ISSUE TITLE
Adding Somfy Shade controller

### ISSUE THREAD

**Issue by humac** [tonesto7/homebridge-smartthings#15]
I'm currently using a custom device handler for my comfy shades that was written by the community.  I don't see an option to add it, it works similar to the garage door tho from what i've seen with a couple differences.

**Comment by pdlove** [comment]
Can you send me which Capabilities it shows? The easiest way to resolve this is to add a line at the top that says Capability "Refresh"

**Comment by humac** [comment]
So I did this and it adds it as a light.  I think this is because the device type is kind of like a dimmer switch but also remembers last state.  So they have it set so that Dim 0% = Down, Dim 50% = My Button (Favourite Position) and Dim 100% = Up.  Here is the device code https://github.com/A5HRAJ/SmartThings/blob/master/somfy_shades.groovy

[SmartThings] Device Added - Group lights, Name Living Room Upper Shades, ID <ID>, JSON: {"name":"Living Room Upper Shades","deviceid":"<ID>","capabilities":{"Switch":1,"Switch Level":1,"Refresh":1},"commands":{"on":[],"off":[],"setLevel":["NUMBER","NUMBER"],"refresh":[],"levelOpenClose":[]},"attributes":{"switch":"off","level":0}}

**Comment by humac** [comment]
When I try adding somfy shade i get the following error in the logs:
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:124
        throw new Error("Cannot add a Service with the same UUID '" + existing.UUID + "' as another Service in this Accessory without also defining a unique 'subtype' property.");
        ^

Error: Cannot add a Service with the same UUID '0000008C-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at SmartThingsAccessory.Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:124:15)
    at new SmartThingsAccessory (/usr/local/lib/node_modules/homebridge-smartthings/accessories/smartthings.js:64:18)
    at populateDevices (/usr/local/lib/node_modules/homebridge-smartthings/index.js:48:19)
    at /usr/local/lib/node_modules/homebridge-smartthings/index.js:66:4
    at /usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:93:13
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:46:27)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)

**Comment by humac** [comment]
![img_0382](https://cloud.githubusercontent.com/assets/9813864/13036733/676e78aa-d33d-11e5-89c1-36e04f33b880.jpg)

Here is an image of the latest device in ST.  Essentially it has 3 states: Open, Closed, and Stop/My (My Favourite Position).  The three buttons are Open = Dim 100%, Closed = Dim 0% and Stop/My = Dim 50%

**Comment by humac** [comment]
So the device added but only sorta works. In idevices app nothing really happens when I tap anything. But in eve app there are up and down arrows and i can adjust the percentages so it goes up and down atleast :) But can't figure out how to control with siri..  If momentary switches work I can go back to that method using my ST virtual switch and a homekit scene to trigger the switch, which i did before.  This may just be too much custom work and I know you need to prioritize.   

**SmartThings] Device Added - Group shades, Name Living Room Upper Shades, ID 587afb93-2017-4cee-b9b3-86186cc110ae**
[SmartThings] Device Added - Group detectors, Name 1st Floor Smoke Alarm, ID f3bb46bf-bc59-45af-a132-b3dc57605506
[SmartThings] Unknown Capabilities: ["**Window Shade**","Smoke Detector","Carbon Monoxide Detector"]
**[SmartThings] Initializing platform accessory 'Living Room Upper Shades'...**
[SmartThings] Initializing platform accessory '1st Floor Smoke Alarm'...

**Comment by pdlove** [comment]
I'm using Apple's Window Covering service for it. They just haven't extended Siri to use it.

**Comment by A5HRAJ** [comment]
[Siri can be used to control Lutron's shades](http://www.cnet.com/news/now-you-can-tell-siri-to-open-your-window-shades/), so it's certainly possible.

Is there anything you would like me to change in the [Somfy Z-Wave Shades device handler](https://github.com/A5HRAJ/SmartThings/blob/master/somfy_shades.groovy) to make things easier for you?

**Comment by pdlove** [comment]
Can I get confirmation that the current state is that this works but isn't Siri controllable? Or that what is going on under the latest version of the plugin... 0.4.6.

**Comment by A5HRAJ** [comment]
Yes, that's accurate. I can change the Target Position in HMCatalog to move the shade, but I haven't found a Siri command that works. Also, the Position State always shows "Closing".
![img_2008](https://cloud.githubusercontent.com/assets/10337059/14038533/6a15fed4-f20f-11e5-8bd0-cd2d2e730be2.PNG)
