### ISSUE TITLE
Any way to remove/decouple the temperature sensor from the contact sensor?

### ISSUE THREAD

**Issue by thayneq** [tonesto7/homebridge-smartthings#155]
I have a bunch of the SmartThings brand multi-sensors. I use them primarily for contact sensors for doors and windows. Using homebridge, each sensor shows up as two devices, a contact sensor and a temp sensor. The problem with that is I am unable to delete the temp sensor portion (I don't want it and it clutters up the HomeKit Interface). I also tried moving the temp sensor portion into a separate "room" but then the contact sensor went along for the ride.

Is there any solution to this?

**Comment by justinfanok** [comment]
I think you would have to modify the device handler in SmartThings to only have it expose the contact sensor portion of it.

**Comment by dibble9012** [comment]
How would the device handler be modified to do this?

**Comment by pdlove** [comment]
I think I should point out that it is being reported to HomeKit as a single device with two services.
I’ve been thinking about splitting up the smart app to provide better control of what device is shown as what HomeKit type(s) but that is future development...
