### ISSUE TITLE
Can not add pdlove as an owner

### ISSUE THREAD

**Issue by berndgill** [tonesto7/homebridge-smartthings#157]
Hi 
I have an European Hub. Whenever I go in the My Smart Apps Tab, there is no settings button, where I could add an owner.

For the first installation I found a workaraound to add an app and to copy the code in.
Now with the new version which Smarthings wants us to install I 'm looking for the code or another way to install it.

Thanks!

Regards

  Bernd

**Comment by pdlove** [comment]
I really thought I added this to the Readme... but I don't see it now... For the European versions, you have to copy/paste from the groovy file in the GitHub... You can find it here: https://github.com/pdlove/homebridge-smartthings/blob/master/smartapps/pdlove/json-complete-api.src/json-complete-api.groovy

**Comment by berndgill** [comment]
Thanks.
Still when I copy this code and create a Smart App I can install it but not open it.
When I want to open it it tries to load and then stops.
Any idea what could be the issue?
I also deleted it and reinstalled it.
