### ISSUE TITLE
SmartThings Simulated Switches are not showing

### ISSUE THREAD

**Issue by tilledminds** [tonesto7/homebridge-smartthings#164]
My other SmartThings physical devices all show correctly but my simulated switches don't seem to be picked up and so I cannot see them in HomeKit - any ideas?

Thanks!

**Comment by burtamcgna** [comment]
Did you refresh your device application and select them after you installing to smartthings hub

**Comment by tilledminds** [comment]
Yes, rerdeshed everything on the ST side as well as restarting Homebridge.
