### ISSUE TITLE
Alarm system device

### ISSUE THREAD

**Issue by ghost** [tonesto7/homebridge-smartthings#167]
Just wondering if there is a way to get the alarm system in smartthings to show up in homekit? I can see all the sensors for the system but no alarm control. I'm using an envisalink connected to my Honeywell alarm and in smartthings I have a device that is my Honeywell panel that lets me see the status and arm/disarm, turn chime on/off, etc. Just wanted to know if it were possible to have the alarm show up in HomeKit too!

**Comment by jacobwtyler** [comment]
+1

**Comment by jacobwtyler** [comment]
Using Konnected panel
