### ISSUE TITLE
Can't Update from Repo

### ISSUE THREAD

**Issue by bondjw07** [tonesto7/homebridge-smartthings#180]
Something is happening when trying to update from the github repo.  I'm getting the following generic error:
<img width="381" alt="screen shot 2017-05-05 at 8 30 57 pm" src="https://cloud.githubusercontent.com/assets/5480627/25768434/000bde60-31d2-11e7-890c-5d8b83c2b165.png">
Which reads:
```
Oh No! Something Went Wrong!
Error: 500: Internal Server Error
URI: /ide/app/doRepoUpdates
Reference Id: 86969824-58f2-4279-a959-2515e49799e4
Date: Sat May 06 00:32:57 UTC 2017
```
This used to be working for me, but I was having trouble getting homebridge to see some new devices I added to SmartThings.  So I decided to delete everything and start fresh.  

I should note that I noticed this same issues before the delete when I tried to publish changes from 0.5.2 to 0.5.5, so I don't think this is due to me deleting and re-adding.

So now I'm totally out of luck until I can get things to pull from the repo again :(

**Comment by ELLIOTTCABLE** [comment]
I'm getting this too (brand-new user, trying to install it for the first time.)
