### ISSUE TITLE
Set "Duration" Attributes for Motion Sensors

### ISSUE THREAD

**Issue by ddorato** [tonesto7/homebridge-smartthings#181]
Is there a way you can set a duration flag to motion sensors in the SmartThings HomeBridge plugin?

An example is in the Hue Plugin:
https://github.com/ebaauw/homebridge-hue/issues/71

**Comment by pdlove** [comment]
That is interesting that I was considering the same thing. I'll start with something defined in the config file to hold the on state for x number of minutes. Sound good?

**Comment by ddorato** [comment]
That sounds amazing!

I think 15-20 minutes as a good start.  I was messing with the HUE integration it it seems HomeKit plays nice with a held setting.

**Comment by pdlove** [comment]
It will be user configurable because I personally want it at 5 minutes based on what I'm seeing in my smartthings logs. 😄

**Comment by ddorato** [comment]
Awesome!  Now if HomeKit only had a setting to have an action happen when Motion is NOT detected :)
