### ISSUE TITLE
Cannot add lock (schlage connect)

### ISSUE THREAD

**Issue by cariacou** [tonesto7/homebridge-smartthings#183]
Hello. 

I am having troubles adding the Schlage Connect Lock. 
It works great in smartthings. When I add it in homebridge under Most Sensors, however, it does not show in my iOS Home. 

Anyone was able to get locks working? Or are they not supported? Thank you

**Comment by model6** [comment]
I checked mine under "Most Devices" and not sensors.  Works great.

**Comment by ebpeterkin** [comment]
Cariacou,

Were you able to get this lock working , getting this device to work with HomeKit is my main reason for installing HomeBridge (unsuccessfully so far).

**Comment by ebpeterkin** [comment]
I got the Schlage Connect working under "Most Devices" as well.
