### ISSUE TITLE
HomeKit Color Temperature

### ISSUE THREAD

**Issue by tpitale** [tonesto7/homebridge-smartthings#187]
I have a bulb that supports color temperature. I can control this via the smartthings app. It seems like this is not available in the Home app on iOS. I'm wondering if you know if this is a limitation of the iOS app itself or something in the bridging between smartthings, the JSON API, or the homebridge server (or perhaps some combination).

Would love to figure out if it would be possible to get this working.

Thanks for a great project!

**Comment by pdlove** [comment]
I'll be doing alot of work on this project over the next month or so. I'll get this in there, but it will only work with IOS 11. Other versions will show an unsupported characteristic.

**Comment by t4ckevint** [comment]
Hey @pdlove is this still something that you're working on? Got it all set up today in iOS 12 and don't see any options for color temperature on any of my smart bulbs from SmartThings. Is there something special I need to modify in the config?
