### ISSUE TITLE
Sprinklers

### ISSUE THREAD

**Issue by hassancy** [tonesto7/homebridge-smartthings#190]
The Rachio sprinkler system, which I use, added operability with SmartThings recently.  I was wondering if the icons for the sprinklers could be synced with the sprinkler icons in HomeKit rather than switch icon.

**Comment by pdlove** [comment]
Are you talking about the new service in IOS 11 or something else?  I don't think I can set a default icon to use but haven't yet reviewed the officially released spec so I'll know for sure by next week.

**Comment by hassancy** [comment]
No.  The change was on the SmartThings side.  They recently expanded the list of devices their hub is interoperable with to include Rachio Sprinklers (www.rachio.com).  So now I can control the sprinklers through my SmartThings app and hence can specify to add it to the JSON API.  It shows up as a switch in the iPhone Home app and I'm wondering if it can be treated as a sprinkler instead?
