### ISSUE TITLE
Sensitive Strips

### ISSUE THREAD

**Issue by hassancy** [tonesto7/homebridge-smartthings#191]
Sensitive Strips are a ZWave open/close sensor that can be connected to a SmartThings hub.  The strips are an option in the Open/Close Sensors part of the SmartThings app.  However, when included in the JSON API smart app, my strip appears in HomeKit but only as an open sensor. When the the SmartThings app shows that strip is in closed state, my iPhone Home app still shows the sensor as open.  

'Device Results' in the JSON API shows the following for this device:
{"name":"Garage Door","basename":"Sensative Strips","deviceid":"DEVICEID","status":"ONLINE","manufacturerName":null,"modelName":null,"lastTime":"2017-06-21T02:50:49+0000","capabilities":{"Battery":1,"Contact Sensor":1,"Configuration":1,"Sensor":1,"Health Check":1},"commands":{"configure":[],"ping":[]},"attributes":{"battery":100,"contact":"closed","checkInterval":28920}}

Is there anything here that needs to be modified for the sensor to sync correctly with the SmartThings app?

**Comment by pdlove** [comment]
If you open it, does the Home app say it is closed? I've double-checked the code and it looks like it should be working correctly. I may just need to get myself an open/close sensor to test with because these have been a constant pain point.
