### ISSUE TITLE
Loaded config.json with 0 accessories and 0 platforms.

### ISSUE THREAD

**Issue by Dat-Tech** [tonesto7/homebridge-smartthings#202]
I have no idea whats going on here. I cannot find any straight information on how the config.jason should be set up, everywhere I look I find different information, this place says you only need 
	{
	   "platform": "homebridge-smartthings.SmartThings",
    	"name": "SmartThings",
        "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
        "app_id": "THIS-SHOULD-BE-YOUR-APPID",
        "access_token": "THIS-SHOULD-BE-YOUR-TOKEN",
        "polling_seconds": 3600,
        "update_method": "direct",
        "direct_ip": "192.168.0.45",
        "direct_port": 8000,
        "api_seconds": 30
	} 
But that does not work, then people say you need the "Bridge" code too but that does nothing also I just have a few devices running through the smart things APP for ease of use until I figure this all out below is what I've built over the past week I've been working on this with looking all around, learning and common sense. Can there be at least 1 person who can actually describe how to set this up (yes my ID, and token are correct, I've been staring at it and checking it for a week now, that's not wrong) all id's are correct and the json is valid.

Just one person who can actually tell me what all needs to be in it, is all I need, thanks so much. or is it just a mystry and no one is allowed to know? I'm tired of wasting my time on nothing this is worthless at this point and not worth the troubble. 

`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": {
		"platform": "homebridge-smartthings.SmartThings",
		"name": "SmartThings",
		"app_url": "https://graph-na04-useast2.api.smartthings.com:443/api/smartapps/installations/",
		"app_id": "This Is Correct",
		"access_token": "This Is Correct To",
		"polling_seconds": 3600,
		"update_method": "direct",
		"direct_ip": "192.168.0.45",
		"direct_port": 8000,
		"api_seconds": 30
	},
	"location": {
		"latitude": xx,
		"longitude": xx,
		"mode": "Working At Desk",
		"name": "Home",
		"temperature_scale": "F",
		"zip_code": "xxxxx",
		"hubIP": "192.168.1.119",
		"smartapp_version": "0.5.5"
	},
	"deviceList": [{
		"name": "Bed lamp",
		"basename": "Bed lamp (Hue Color Temperature)",
		"deviceid": "03e5eea4-5d5c-xxxcorrect numberxxx",
		"status": "ONLINE",
		"manufacturerName": null,
		"modelName": "LTW004",
		"lastTime": null,
		"capabilities": {
			"Switch": 1,
			"Switch Level": 1,
			"Refresh": 1,
			"Sensor": 1,
			"Actuator": 1,
			"Color Temperature": 1,
			"Health Check": 1,
			"Light": 1
		},
		"commands": {
			"on": [],
			"off": [],
			"setLevel": ["NUMBER", "NUMBER"],
			"refresh": [],
			"setColorTemperature": ["NUMBER"],
			"ping": []
		},
		"attributes": {
			"switch": "off",
			"level": 72,
			"colorTemperature": 6536,
			"checkInterval": null
		}
	}, {
		"name": "Desk lamp",
		"basename": "Desk lamp (Hue Color Temperature)",
		"deviceid": "edb4390b-d331-xxxcorrect numberxxx",
		"status": "ONLINE",
		"manufacturerName": null,
		"modelName": "LTW004",
		"lastTime": null,
		"capabilities": {
			"Switch": 1,
			"Switch Level": 1,
			"Refresh": 1,
			"Sensor": 1,
			"Actuator": 1,
			"Color Temperature": 1,
			"Health Check": 1,
			"Light": 1
		},
		"commands": {
			"on": [],
			"off": [],
			"setLevel": ["NUMBER", "NUMBER"],
			"refresh": [],
			"setColorTemperature": ["NUMBER"],
			"ping": []
		},
		"attributes": {
			"switch": "on",
			"level": 90,
			"colorTemperature": 6536,
			"checkInterval": null
		}
	}, {
		"name": "Fan light",
		"basename": "Fan light (Hue Extended Color)",
		"deviceid": "cecfcd01-f751-xxxcorrect numberxxx",
		"status": "ONLINE",
		"manufacturerName": null,
		"modelName": "LCT014",
		"lastTime": null,
		"capabilities": {
			"Switch": 1,
			"Switch Level": 1,
			"Refresh": 1,
			"Color Control": 1,
			"Sensor": 1,
			"Actuator": 1,
			"Color Temperature": 1,
			"Health Check": 1,
			"Light": 1
		},
		"commands": {
			"on": [],
			"off": [],
			"setLevel": ["NUMBER", "NUMBER"],
			"refresh": [],
			"setHue": ["NUMBER"],
			"setSaturation": ["NUMBER"],
			"setColor": ["COLOR_MAP"],
			"setColorTemperature": ["NUMBER"],
			"ping": [],
			"setAdjustedColor": []
		},
		"attributes": {
			"switch": "off",
			"level": 100,
			"hue": 54,
			"saturation": 92,
			"color": "#F4FCFF",
			"colorTemperature": 6536,
			"checkInterval": null
		}
	}]
  }
`

**Comment by ebpeterkin** [comment]
This one:

{
    "bridge": {
        "name": "Homebridge",
        "username": "YOUR-MAC-ADDRESS",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "JSON API",
    "platforms": [
        {
            "platform": "SmartThings",
            "name": "SmartThings",
            "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "YOUR-UNIQUE-APP-ID",
            "access_token": "YOUR-UNIQUE-ACCESS-TOKEN"
        }
    ]
}

Which I found here:  

http://squidstack.com/smarthome/configuring-smartthings-to-homekit-with-homebridge/

worked well for me. The only thing I had to change was the app URL (you need to figure out which URL works for you)
