### ISSUE TITLE
ios11 home app is showing one device as unsupported

### ISSUE THREAD

**Issue by bdee1** [tonesto7/homebridge-smartthings#204]
I am runnign the ios11 beta on my iphone and for some reason, in the home app, it is showing one of my zwave plug in modules as an unsupported device.

The device previously worked with homebridge and it works fine with smartthings.

I woudl be happy to provide any additional details or logs necessary to troubleshoot.  thanks!

**Comment by pdlove** [comment]
Are you fully updated on homebridge? A fix was published last week for this issue.

**Comment by bdee1** [comment]
Nope I haven’t updated recently. I am sure that’s the issue. Any special
Instructions for the update?

**Comment by pdlove** [comment]
Nothing special. Be aware it is Homebridge that needs updating and not this plugin.

**Comment by bdee1** [comment]
ok great - thanks!   will i need to remove and re-add the homebridge in the ios home app in order to get the unsupported device back?

**Comment by pdlove** [comment]
Reports are mixed. Some users have reported the need to delete the persist file and recreate the association to IOS but others have said it worked seamlessly.  "npm update -g homebridge" should get you where you need to be.

**Comment by bdee1** [comment]
ok great - i will test it when i get home tonight.  thanks for the prompt response!!
