### ISSUE TITLE
GE Motion Switch 26931 (Motion and Switch in one)

### ISSUE THREAD

**Issue by OneFast440** [tonesto7/homebridge-smartthings#207]
I have several of the GE Motion Switches - 26931 (https://byjasco.com/products/ge-z-wave-plus-smart-motion-switch), to get these to work they require a customer device handler. The one that works great is by mlebaugh (https://github.com/mlebaugh/smartthings/blob/master/devicetypes/mlebaugh/ge-motion-switch-26931.src/ge-motion-switch-26931.groovy). 

My issue is that these ONLY connect to HomeKit as a motion detector (which work great, they are near instant) however, I cannot get them to work as light switches. Any assistance would be great!

**Comment by mlciskey** [comment]
I think the problem may be that the device handler has both the Button and Switch capability and if I'm reading the code in homebridge-smartthings it finds the Button capability first and then ignores the Switch capability.

**Comment by turnepf** [comment]
@OneFast440 I have one and it shows up as both a light switch and a motion detector for me. Perhaps a recent device handler update has resolved your issue.

**Comment by skazzyskills** [comment]
@turnepf Hey..I have 4 of these and am new to Homebridge. I have the ST plugin going, but the switches are showing as 'unsupported'. How did you get yours to be recognized as a switch? Any help appreciated!

**Comment by turnepf** [comment]
@skazzyskills - I'm using this device handler: 

GE Motion Dimmer Switch 26933 
from this GitHub repo:
mlebaugh/smartthings (master)

**Comment by OneFast440** [comment]
> @OneFast440 I have one and it shows up as both a light switch and a motion detector for me. Perhaps a recent device handler update has resolved your issue.

Mine is showing up as motion and button (not a switch). The button does not allow me to assign on/off capabilities. 

I'm using GE Motion Switch (Model 26931) DTH ver. 1.0.5

**Comment by OneFast440** [comment]
@mlciskey How do you suggest I re-write it to work?

https://raw.githubusercontent.com/MichaelStruck/SmartThingsPublic/master/devicetypes/michaelstruck/ge-motion-switch-26931.src/ge-motion-switch-26931.groovy

**Comment by skazzyskills** [comment]
@turnepf Sorry, I'm new to all this. What do I do with that device handler code?

**Comment by skazzyskills** [comment]
I'm using GE Motion Switch 26931

**Comment by skazzyskills** [comment]
Ok, using GE Z-Wave Motion Sensor Switch (Model 26933) I was able to get a switch that I can turn on in Homebridge.
