### ISSUE TITLE
Polling Question

### ISSUE THREAD

**Issue by JDogg016** [tonesto7/homebridge-smartthings#208]
I notice the default polling is set to 3600 seconds which is hourly?

Why do high?

Would it benefit the system to poll every 60 seconds or so.

**Comment by pdlove** [comment]
The poll is simply to make sure everything is right locally. Normal changes are streamed to the plugin from the hub as they happen. If you poll more often than every 10 minutes then Smartthings may shut your smart app down. I don’t have a firm minimum from them, but their developers instructed the hourly to reduce impact on their servers. Make sure direct connect is working and you’ll be good.

**Comment by JDogg016** [comment]
Thanks for the information.  I noticed when I load the Home App (iOS 11) most devices using the plugin say ‘Updating’ and I did not know whether this was the result of polling.



Justin Bennett, Esq.

Personal E-Mail Account. Although this was sent from my personal e-mail this communication may contain privileged or other confidential information. If you are not the intended recipient, or believe that you have received this communication in error, please do not print, copy, retransmit, disseminate, or otherwise use the information contained herein. Also, please notify sender that you have received this communication in error, and delete the copy thereof you have received. Thank you.

**Comment by pdonovan** [comment]
Does this polling period affect how long it takes for a new Smartthings device selected in the JSON Complete smart app to appear in Home/Homekit?

ie. I selected to ST Moisture Sensors. I can see them in the JSON, but they're not in iOS 11 Home yet. Or is there something else I need to do to get the items to appear? I'm not at home now, but I have an Apple TV there. Does that make a difference?
