### ISSUE TITLE
Adding SHM as a Security device type?

### ISSUE THREAD

**Issue by JangoBritt** [tonesto7/homebridge-smartthings#210]
As HomeKit now supports Security systems, any chance of getting SmartHomeMonitor added as a Device Type?

**Comment by jacobwtyler** [comment]
+1

**Comment by scottrobertson** [comment]
Out of interest @tonesto7 is there any movement on this? It would be nice to have a device type like:

https://github.com/MiguelRipoll23/homebridge-securitysystem#readme
