### ISSUE TITLE
JSON Complete API - Not showing under "My Apps"

### ISSUE THREAD

**Issue by parsamanesh** [tonesto7/homebridge-smartthings#213]
> ...
> Click on the app in the list and then click "App Settings"
> Scroll down to the OAuth section and click "Enable OAuth in Smartapp"
> Select "Update" at the bottom.
> In the SmartThings App, goto "Marketplace" and select "SmartApps". At the bottom of the list, select "My Apps"
> Select "JSON Complete API" from the list.
> 

I have followed all steps correctly up until the point in the instructions where it says to select the JSON Complete API in the My Apps list. 
When I click the My Apps button on iOS, i get a small spinner and then it disappears and nothing happens. I just stay on the screen with the My Apps button. Its as if the My Apps section is empty and it can't get to it or something.
I am logged in to the same smartthings account on the device as my Mac on site is, not sure why this is happening?
![img_24eb3401e79e-1](https://user-images.githubusercontent.com/15655085/31609075-9f1a9bfe-b26a-11e7-9e3e-7bd5457fc35a.jpeg)
![screenshot 2017-10-16 12 39 32](https://user-images.githubusercontent.com/15655085/31610199-19848edc-b26f-11e7-8ea4-c45b9a504e52.png)

**Comment by sanghviharshit** [comment]
Were you able to resolve this issue? I am also stuck on this step, can't see it under My Apps.

**Comment by sanghviharshit** [comment]
Never mind, I found the issue. The app was not published.

**Comment by efetzer** [comment]
I am having this same issue. But it shows published, but I get nothing in the apps "My Apps" section

<img width="1930" alt="screen shot 2017-11-21 at 8 33 48 pm" src="https://user-images.githubusercontent.com/11339558/33108799-50a91704-cefb-11e7-8a84-b563f7ed2d29.png">
