### ISSUE TITLE
Seeing a HAP Warning Error Since Update, Any ideas ?

### ISSUE THREAD

**Issue by Wildcat1** [tonesto7/homebridge-smartthings#215]
@pdlove / all 
Seeing this issue recently after updating. Anyone have any ideas on what its referencing and how to fix:

'HAP Warning: Characteristic not in required or optional characteristics for service . Adding anyway.' 

Thanks

**Comment by defatpm** [comment]
I have something similar:

`[2018-2-12 22:03:28] [SmartThings] Direct Connect Is Listening On 192.168.1.138:8000
HAP Warning: Characteristic 00000054-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000003E-0000-1000-8000-0026BB765291. Adding anyway.`

In the Home app, the devices are stuck in "updating" status.
