### ISSUE TITLE
Multiple JSON Complete API's - MarketPlace - My Apps

### ISSUE THREAD

**Issue by burtamcgna** [tonesto7/homebridge-smartthings#218]
Every time I add a new device to Smartthings and then go to add it to the JSON device list, clicking "DONE" result in an error, it is typically associated with the Secret's not matching.  What I noticed is I have MULTIPLE JSON's registered on the device it seems.  I have only installed a SINGLE JSON COMPLETE API from MarketPlace -> My Apps.  

I have spent 10 minutes removing JSONS from my iPhone.  Still, there are more it seems.

What's going on?  What am I doing wrong?

Error:  There was a problem processing you request.

**Comment by jamesg311** [comment]
When you want to make an update to your device list, go to Automation > SmartApps and edit from there. This will keep the JSON configuration up to date and not change app_id or authentication token.  

If you go to Marketplace, it essentially creates another instance of the SmartApp. It took me awhile to figure this out and after I did I noticed I had like 5 or 6 JSON API SmartApps which was causing problems. I removed all the wrong ones and no longer have this issue.
