### ISSUE TITLE
Status not getting updated with homekit commands

### ISSUE THREAD

**Issue by popepay** [tonesto7/homebridge-smartthings#222]
Hello,

I use homebridge-smartthings to control some zwave (smartthings) light switches (DZ6HD) from homekit.
When I use homebridge to send commands (on/off), the homekit status only gets updated ~15% of the time. 
The Smartthings status works fine. Homekit/Homebridge however gets out of sync. 

Is anyone else having the same issue?
Happens often through homekit scenes (maybe because there are a few simultaneous commands triggered?)

**Comment by dp917** [comment]
Same happening to me. I’m wondering if changing the polling time to be more often if it’d help.
