### ISSUE TITLE
Need Opinion on Smartthings API

### ISSUE THREAD

**Issue by pdlove** [tonesto7/homebridge-smartthings#225]
I know there are still some issues to sort out and I see them in my own installation so know I am working on that more now that I have been in the past.

You may or may not be aware that SmartThings has released a REST API for easier access to their framework. This gives the opportunity to eliminate alot of the clumsiness of using the smartapp to access the devices including a removal of the need to select individual devices. This comes with one limitation. In order to get the cloud to send back device status in real-time it needs an https connection into your homebridge device.

There are three ways to accomplish this:
1) Use port forwarding on your firewall. I don't like this option because of the configuration hassle and the potential security concerns.
2) Use ngrok to redirect and external fee internally without having to open a firewall port. I like this solution because it handles all of the https communications. I don't like it because the URL it gives changes every time you run it and it's an additional step.
3) I'm working on developing a kind of proxy connector that would sit on an Azure or AWS virtual machine. This would allow for homebridge-smartthings to connect to that and for it to communicate with smartthings for receiving subscription data. I'm not sure how the community would feel about this because the update information would flow back through something I'd be hosting in the cloud. Full source of the proxy connection and instructions for setting it up would be available.

I'm probably going have all 3 available as an option because that wouldn't require much effort while also retaining support for the existing smartapp implementation.  I just wanted to know if any of you people using this would have an opinion.

On a side note, I've been told that a local REST API that connects to your local hub is being considered. That would eliminate this need for the cloud.

**Comment by LeBlaaanc** [comment]
hey @pdlove, firstly let me thank you for your work on this project. It's really nice to have HomeKit support with an easy to use and understand hub. I usually don't say many nice things about SmartThings but I just gave HASS a try and I couldn't even get it to work with my lock properly.

That said, I would personally be fine with port forwarding because most of us understand how it works. I am curious however what exactly ST is sending to us through this method? I'm guessing if a thermo setpoint is updated then it would report to us through this HTTPs endpoint? Any idea what would be available locally?

**Comment by cnnn** [comment]
+1 for port forwarding.

**Comment by jesseking3** [comment]
-5 on port forwarding. It’s the least secure, and I wouldn’t do it.

**Comment by billyzoellers** [comment]
+1 for port forwarding. The local REST API sounds awesome though... surely hope they make that happen.

**Comment by JDogg016** [comment]
Any method would be fine... whatever makes this happen
