### ISSUE TITLE
Can't establish connection to SmartThings Hub

### ISSUE THREAD

**Issue by davpel** [tonesto7/homebridge-smartthings#237]
I'm a brand new Homebridge user. I have successfully installed the Homebridge server on my Synology running in Docker. I installed the SmartThings plugin and followed all of the configuration instructions. JSON Complete API shows up in my SmartThings app under Automation/SmartApps and I have enabled the devices I need. I'm able to add HomeBridge to my Homekit, but none of my SmartThings devices appear if I set it up using direct connection. 

When I start Homebridge, I get:

[2018-2-4 17:15:15] Homebridge is running on port 51826.
[2018-2-4 17:15:15] [SmartThings] Direct Connect Is Listening On 192.168.1.45:8000

However, I do not get the message "[SmartThings] SmartThings Hub Communication Established"

The IP of my SmartThings hub is 192.168.1.50. There is no firewall running on my Synology.

Any idea how to fix this? The plugin does work if I configure it using "api" or "pubnub", but I would prefer the direct connection.

**Comment by simonrb2000** [comment]
Did you manage to fix this? I can see and operate devices in HomeKit but can't get Direct Updates to work. I too do not receive the Communication Established. 

Many Thanks

**Comment by simonrb2000** [comment]
I fixed this by setting the Direct IP address as the same as my Raspberry Pi that is running Homebridge.
