### ISSUE TITLE
Yale Conexis Battery 0% Warning

### ISSUE THREAD

**Issue by greztaylor** [tonesto7/homebridge-smartthings#246]
Hi, I've added my Yale Conexis L1 Smart Lock to the Smartthings Hub (via a z-wave module) then onwardly to the Apple Home app on my iPhone via Homebridge.  Everything works great in the app and via Siri but I have an annoying 'Low Battery' warning on the device in the Home app that can't be turned off.  Has anyone experienced something similar or has a view on how to remove the Low Battery warning?  any help in advance is greatly appreciated 

Graham

**Comment by VeniceNerd** [comment]
I’m interested in doing this exact setup! Is the lock still working reliably for you?
