### ISSUE TITLE
Consistently deletes devices from rooms, then re-adds to default room on restarts / power loss

### ISSUE THREAD

**Issue by drumfreak** [tonesto7/homebridge-smartthings#260]
There have been several instances where my homebridge was either power cycled due to a storm, or other power loss, and for some reason, after a period of connectivity loss from the SmartThings hub, all of the devices get removed from homebridge, and later when a connection is re-established, they are re-added but in the default room.  This is extremely painful when using smartthings / homekit to do automations as I have to re-program them almost every couple of days. 

In effort to stabilize the power, I added backup batteries to the smart things hub, and put the raspberry pi on a UPC battery backup, yet even in the process of that, all my smartthings devices were removed / added back to the default room, or whichever room my homebridge is in on the homekit app.

Any ideas? Thanks!

**Comment by felipekoblinger** [comment]
+1
I'm having this issue too.

**Comment by jamesg311** [comment]
Any update here? Have you found a solve? If so, please post.
