### ISSUE TITLE
myQ Garage Door not showing up as an Device option.

### ISSUE THREAD

**Issue by rchoughton** [tonesto7/homebridge-smartthings#262]
I have installed the brbeaird/SmartThings_MyQ smart app that brings a Lift Master myQ garage door into smartthings. At one time it showed up as an option to select, but with recent updates it does not show up as an option anymore. Is there a way to resolve this?

**Comment by jeffgloe** [comment]
I do not have this specific opener, but do have one. In order for me to get it to be an option for selection, I had to add the following in the code.

dynamicPage(name: "copyConfig", title: "Config", install:true, uninstall:true) {
        section("Select devices to include in the /devices API call") {
            paragraph "Version 0.4.1"
            input "deviceList", "capability.refresh", title: "Most Devices", multiple: true, required: false
            input "sensorList", "capability.sensor", title: "Sensor Devices", multiple: true, required: false
            input "switchList", "capability.switch", title: "All Switches", multiple: true, required: false
            input "momentaryList", "capability.momentary", title: "Momentary Switches", multiple: true, required: false
            paragraph "Devices Selected: ${deviceList ? deviceList?.size() : 0}\nSensors Selected: ${sensorList ? sensorList?.size() : 0}\nSwitches Selected: ${switchList ? switchList?.size() : 0}"
        }



and



def renderDevices() {
    def deviceData = []
        deviceList.each { 
        	deviceData << [name: it.displayName, deviceid: it.id, capabilities: deviceCapabilityList(it), commands: deviceCommandList(it), attributes: deviceAttributeList(it)]
	}    
        sensorList.each  { 
        	deviceData << [name: it.displayName, deviceid: it.id, capabilities: deviceCapabilityList(it), commands: deviceCommandList(it), attributes: deviceAttributeList(it)]
	}
        switchList.each  { 
        	deviceData << [name: it.displayName, deviceid: it.id, capabilities: deviceCapabilityList(it), commands: deviceCommandList(it), attributes: deviceAttributeList(it)]
	}
    momentaryList.each  { 
        	deviceData << [name: it.displayName, deviceid: it.id, capabilities: deviceCapabilityList(it), commands: deviceCommandList(it), attributes: deviceAttributeList(it)]
	}
    return deviceData
}

def findDevice(paramid) {
	def device = deviceList.find { it.id == paramid }
  	if (device) return device
	device = sensorList.find { it.id == paramid }
	if (device) return device
  	device = switchList.find { it.id == paramid }
    if (device) return device
  	device = momentaryList.find { it.id == paramid }

	return device


The momentary lines are the ones I added.
