### ISSUE TITLE
I get it setup and fully functional, then after about a week all devices are unavailable.

### ISSUE THREAD

**Issue by gizmo8500** [tonesto7/homebridge-smartthings#272]
My home has about 72 smartthings devices. I also have a 4K apple TV.

This is the 3rd time that I have setup smartthings, got everything working, setup all my rooms, able to control all devices with the home app or siri, and then seemingly out of the blue all devices show not responding. I can no longer control any device with homekit. The strangest part is this, even though I can't control the devices, I still get notifications from them for events such as unlocking the front door etc. This tells me that some kind of communication is still working. 

The logs that I looked at for homebridge seem to indicate the service starts up with no issues. It indicates it is communicating with the hub. In the past the only way I have determined to resolve the issue is to delete the home in homekit, and then re-pair it. Obviously this is impractical as it takes quite some time to setup all the rooms and devices again. Does anyone have any idea what might be going on? Could the Apple TV somehow be interfering? The apple TV is the only device that is responding in the home app.

**Comment by Quiqui64** [comment]
I’m seeing a similar situation we my Home has a power loss. But all I need to resolve the issue is to reboot my Raspberry Pi. I’m guessing that it’s do too syncing issues between my appleTv and the Pi when there powering back up. I working on getting a battery backup for my Pi.

**Comment by gizmo8500** [comment]
I just wish there was a way to determine why I can get notifications but all devices are unavailable and uncontrollable.

**Comment by jamesg311** [comment]
I’m dealing with this too. Did you ever find a solve? I reboot my Homebridge from my Mac a couple of times a week with no problems but almost exactly 1 week after getting everything setup and working, all the devices disappear and then after a Homebridge reboot they all appear in Default Room.

**Comment by gizmo8500** [comment]
I have not. I find that rebooting my Mac tends to be the instigator of everything becoming not available.
