### ISSUE TITLE
Bali (Somfy) Z-Wave cellular window shades register as light accessories vs shade

### ISSUE THREAD

**Issue by konstasy** [tonesto7/homebridge-smartthings#273]
@pdlove,

I am new to homebridge and homebridge-smartthings, so apologies if this is a newbie question.

I am trying to use my Bali (Somfy) Built-in Z-Wave cellular window shades with homebridge-smartthings.  They open fine, but will not close.  My guess is because they are being added as a light vs a shade.  The exact message is "[SmartThings] Device Added - Group lights, ...".  They will lower if I use a % (1-99), but 0% and a close will not lower them.

I have tried both the following Device types in my SmartThings Hub, but both still add as a light:
- Z-Wave Window Shade
- Springs Window Fashions Shade

The shades works properly with the SmartThings Hub via the new SmartThings App (iOS) and SmartThings Classic App (iOS) with either of the above Device Types.

I also attempted to use a custom Device Handler (imnotbob/somfy-shades), this did get them to add as a shade with homebridge-smartthings, but the handler will not control the shades properly via the SmartThings Hub or homebridge-smartthings.  The exact message is "[SmartThings] Device Added - Group shades, ...", but obvously the Device Handler is not compatible with the newer shades.

Is there a way to force them to register as shades vs lights?  Something I can do in the accessories config maybe?

Thank you,
Konstas

**Comment by konstasy** [comment]
PS: I am getting "[SmartThings] Unknown Capabilities: ["Health Check","Window Shade"]" after the devices are added / before initialization.  Thanks again.

**Comment by nmelanson75** [comment]
Did you get this resolved as I am having the same issue.

**Comment by konstasy** [comment]
No, sorry.

@pdlove, I am sure you are very busy, any chance you can give us a hint?  Thank you.
