### ISSUE TITLE
Device Skipped - Inovelli Switch

### ISSUE THREAD

**Issue by joe248** [tonesto7/homebridge-smartthings#274]
`
[2018-8-1 10:52:39] [SmartThings] Device Skipped - Group  button, Name Kitchen Table Light, ID XXX, JSON: {"name":"Kitchen Table Light","basename":"Z-Wave Switch","deviceid":"XXX","status":"ONLINE","manufacturerName":"null","modelName":null,"lastTime":"2018-08-01T15:49:20+0000","capabilities":{"Switch":1,"Polling":1,"Configuration":1,"Refresh":1,"Button":1,"Sensor":1,"Actuator":1,"Holdable Button":1},"commands":{"on":[],"off":[],"poll":[],"configure":[],"refresh":[],"pressUpX1":[],"pressDownX1":[],"pressUpX2":[],"pressDownX2":[],"pressUpX3":[],"pressDownX3":[],"pressUpX4":[],"pressDownX4":[],"pressUpX5":[],"pressDownX5":[],"holdUp":[],"holdDown":[],"setAssociationGroup":["NUMBER","NUMBER","ENUM","NUMBER"]},"attributes":{"switch":"off","button":"held","numberOfButtons":6,"supportedButtonValues":null,"lastActivity":"2018 Aug 01 Wed 10:49:20 AM","lastEvent":" Hold ▼","firmware":"1.03"}}
`

I'm using this Inovelli switch with their custom SmartThings device handler that allows for scene control: https://inovelli.com/shop/smart-light-switches/z-wave-switch-on-off-scenes-repeater/

At this point I don't really care about having the scene control working with Homekit, but I'd at least like the regular switch part to work.  Is there a change I can make in the homebridge-smartthings code to get it working?

**Comment by pabowles** [comment]
Having the same issue with same switch and device handler. All other devices are coming through SmartThings-homebridge with no issues but my 4 inovelli switches just say device skipped.

**Comment by InovelliUSA** [comment]
Hmmm, no other information on why it was skipped? This is a big guess, but the first line says "Group button". Is it classifying it as a button device because it has the button capability? You could try to remove the following lines to see if it makes a difference:

capability "Button"
capability "Holdable Button"

**Comment by pabowles** [comment]
So I was actually able to get passed this issue by switching to the smartthings-homebridge-tonesto7 version of Homebridge (I didn't realize it had been forked). With this installed, the switches all show up in Homekit but they do not actually work. When you tap one to turn on or off it just spins and says device not responding.

**Comment by InovelliUSA** [comment]
What version of the device handler do you have? There should be a date up towards the top?

**Comment by pabowles** [comment]
It's the most recent version from early August. I had just updated it before switching over to the new version of homebridge that was forked.

**Comment by joe248** [comment]
I was on the 6/20/18 version, commented out the "Button" and "Holdable Button" lines, restarted Homebridge, and it worked!  I then updated to the 8/3/18 version and also commented out those lines, restarted, and it's still working.

Am I losing any functionality or setting myself up for other bugs by leaving those capabilities disabled?

**Comment by erocm123** [comment]
On the SmartThings side you would be losing the scene support. :( Sounds like there is a possible bug in homebridge that it is assuming the device is a button device (and not a switch) when the button capability is there.

**Comment by joe248** [comment]
@erocm123 thanks for taking a look at this and pointing me in the right direction!

As mentioned above it looks like this is failing because the device is being added as a button instead of a switch, but the button code is not implemented.  The button deviceGroup was added here but it doesn't add any services:

https://github.com/pdlove/homebridge-smartthings/commit/3958e4de18d7acce258a30bb357977acc9a05714#diff-ab2a2362f7fcb28ab2d4b5a489a6c399R220

@pdlove can we comment out the button code since it doesn't do anything and is interfering with the Inovelli switch?
