### ISSUE TITLE
Would anybody like to take over this plugin?

### ISSUE THREAD

**Issue by pdlove** [tonesto7/homebridge-smartthings#277]
I haven't had time in far too long to work on this and my smartthings hub recently died so I've switched to the hubitat hardware... but with it totally replaced with Home Assistant driving the USB stick directly.
In short I no longer have the hardware to test any work on this.
This plugin is in desperate need of being upgraded to the newer Homebridge API to prevent some of the room resets and I'm more than happy to give another developer pointers on doing that.

**Comment by JangoBritt** [comment]
Oh dear. This is bad news indeed.

I hope you find somebody!

**Comment by jelockwood** [comment]
You can probably find a cheap hub on eBay. If you were in the UK I could loan you one.

**Comment by jdebardi** [comment]
Looks like someone has forked it https://github.com/tonesto7/homebridge-smartthings-tonesto7

Be nice if they took control of this repo rather than having a new npm package.
Maybe pdlove could reach out to them?

**Comment by tonesto7** [comment]
@pdlove I would love to take this over

**Comment by tonesto7** [comment]
@pdlove Also if you could transfer the package ownership on npm to me I would appreciate it :)
https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

**Comment by pdlove** [comment]
Absolutely. Let me get my npm information and I'll transfer that now, as well as the github.

**Comment by pdlove** [comment]
I'll check again in a couple of days to make sure everything processed through. Feel free to remove me as a maintainer or contributor.

**Comment by tonesto7** [comment]
Thanks Paul I really appreciate all the work you've put into this.

**Comment by pdlove** [comment]
I'm thankful someone continued working with it after I moved away from SmartThings and Homebridge. Let me know if you need anything on this that I can help with but I'm pretty sure you know it really well already from some of your other work.
