### ISSUE TITLE
Z-wave thermostat showing as Temp sensor in Homekit

### ISSUE THREAD

**Issue by jblakeney82** [tonesto7/homebridge-smartthings#281]
Hey all I hav read your thread from a few years back regarding this issue however my thermostat will not show properly in Homekit. It will show temp only and no controls. 

Any Idas?

**Comment by dkcoleman** [comment]
I have the exact same issue and am still trying to find a way to fix this.

**Comment by dkcoleman** [comment]
I have the exact same issue and am still trying to find a way to fix this.
