### ISSUE TITLE
Add support for Samsung Washer and Driers

### ISSUE THREAD

**Issue by ablyler** [tonesto7/homebridge-smartthings#284]
Example of output from the homebridge log when I enabled the washer and drier from the SmartThings app:

`[SmartThings] Device Skipped - Group unknown, Name Washer, ID 56d1263b-10ae-4663-8b57-02675e0ef9a6, JSON: {"name":"Washer","basename":"Samsung Washer","deviceid":"56d1263b-10ae-4663-8b57-02675e0ef9a6","status":"ACTIVE","manufacturerName":null,"modelName":null,"lastTime":"2019-01-19T04:17:42+0000","capabilities":{"Refresh":1,"Sensor":1,"Consumable":1,"Timed Session":1},"commands":{"refresh":[],"setConsumableStatus":["ENUM"],"start":[],"stop":[],"pause":[],"cancel":[],"setCompletionTime":["DATE"],"subscribeDevice":[],"unsubscribeDevice":[],"setOperationRun":[],"setOperationPause":[],"sendRequest":["STRING","STRING","STRING"]},"attributes":{"consumableStatus":null,"sessionStatus":"Run","completionTime":null,"operationState":"Run","operationThingsState":"Disconnected","remoteControlEnabled":"false","alarms":"HotWarning","isConnected":"disconnected","operationProgress":"None"}}
homebridge_1  | [1/19/2019, 7:21:52 AM] [SmartThings] Device Skipped - Group unknown, Name Dryer, ID d0b36540-ece7-4ef3-b60e-f698f3979650, JSON: {"name":"Dryer","basename":"Samsung Dryer","deviceid":"d0b36540-ece7-4ef3-b60e-f698f3979650","status":"ACTIVE","manufacturerName":null,"modelName":null,"lastTime":"2019-01-19T12:21:50+0000","capabilities":{"Refresh":1,"Sensor":1,"Consumable":1,"Timed Session":1},"commands":{"refresh":[],"setConsumableStatus":["ENUM"],"start":[],"stop":[],"pause":[],"cancel":[],"setCompletionTime":["DATE"],"subscribeDevice":[],"unsubscribeDevice":[],"setOperationRun":[],"setOperationPause":[],"sendRequest":["STRING","STRING","STRING"]},"attributes":{"consumableStatus":null,"sessionStatus":"Run","completionTime":null,"operationState":"Run","operationThingsState":"Monitoring_Run","operationProgress":"Cooling","remoteControlEnabled":"false","alarms":"Vent_Lev0","isConnected":"connected"}}`

**Comment by ferdi2005** [comment]
YES PLEASE ADD SUPPORT!

**Comment by simonrb2000** [comment]
Yes please
