### ISSUE TITLE
error causing  losing all Home settings

### ISSUE THREAD

**Issue by Anuj79** [tonesto7/homebridge-smartthings#286]
have had this multiple times that when homebride is restarted i lose all the settings  on the home app.  it doesnt happen everytime but finally was able to see this error.  

 raspberrypi homebridge[474]: error at req:  getaddrinfo EAI_AGAIN graph-na02-useast1.api.smartthings.com:443
 raspberrypi homebridge[474]: [2019-1-30 15:44:12] [SmartThings] Invalid Response from API call
 raspberrypi homebridge[474]: [2019-1-30 15:44:12] [SmartThings] Unknown Capabilities: []

i am guessing once this happens homebridge loses all the devices and on the next restart it seems them as new .. any thoughts on how this can be prevented.

**Comment by phughes** [comment]
I've also experienced this.
