### ISSUE TITLE
Samsung OCF Robot Vacuum

### ISSUE THREAD

**Issue by psmurashov** [tonesto7/homebridge-smartthings#293]
Hi !
Help! It's not working [robot vacuum] Samsung (Samsung OCF Robot Vacuum).
//=======================
[SmartThings] Error received type java.lang.NullPointerException - An unexpected error occurred.
[SmartThings] Unknown Capabilities: []

**Comment by miguelatv** [comment]
Hi, I am also interested in setting the robot vacuum. 

When I set it as a device, I get a switch added to homekit. The switch, when triggered, causes the robot to make a sound, it does not however change any state of the robot. 

Is there a way to choose what the switch changes in the robot? Ideally I would like to turn the switch ON to make the robot clean, and switch it OFF to make it go recharge. Any ideas on how to achieve this?
