### ISSUE TITLE
ST-Community-Installer Smartapp page broken links

### ISSUE THREAD

**Issue by alzbookstore** [tonesto7/homebridge-smartthings#299]
The links for Smartapps, including HomeBridge on the ST-Community-Installer SmartApp, don't load the appropriate SmartApp. Instead, the main page reloads. This refers to the HomeBridge SmartApp nested in the ST-Community-Installer SmartApp located in the SmartThings Classic app -> Marketplace -> SmartApps -> My Apps -> ST-Community-Installer. 

Once in there, tapping on the 'Installer Home' loads the Community Installer page with many SmartApps. When I tap on HomeBridge, it just jumps back to the top of the page. This occurs with all apps on that page. I reproduced it on an iPad and a Mac. It seems that every link on that page just redirects to itself, reloading the page.

ST-Community-Installer: https://graph.api.smartthings.com/api/smartapps/installations/211fc116-b67f-4010-ae8b-d007a77e192f/installStart?access_token=0fbefe3c-6945-44b1-aea1-7f435fe8b6d0#

This is 100% reproducible. I'm now blocked attempting to install HomeBridge.

**Comment by designorant** [comment]
I was able to reproduce that. Manual installation via GitHub went smooth though.

**Comment by alzbookstore** [comment]
It looks like that particular issue is resolved, except my issue now is that I don't have access to add the repo. I'm getting this message:
"You don't have access to tonesto7/st-community-installer"
My GitHub integration is in place, and I also tried tonesto7/homebridge-smartthings as the instructions vary between two pages.

Anyone else hit this?

**Comment by alzbookstore** [comment]
Sorry, I should create a separate issue for that. Closing this one now that it's resolved.
