### ISSUE TITLE
No access to repo via SmartThings IDE

### ISSUE THREAD

**Issue by alzbookstore** [tonesto7/homebridge-smartthings#303]
-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The SmartApp and Device Handler are using the latest code available.
-  [Doesn't show in Device Handlers] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

When attempting to add the repo in my SmartThings IDE, it tells me I don't have access to the repo:
"You don't have access to tonesto7/homebridge-smartthings"

I also attempted with tonesto7/st-community-installer since the instructions vary between these two locations:
http://thingsthataresmart.wiki/index.php?title=Community_Installer_(Free_Marketplace)
https://www.npmjs.com/package/homebridge-smartthings

This also occurs on both the My SmartApps and My Device Handlers pages. I have attempted updating and re-publishing the SmartApp and verified GitHub integration.

Am I missing something?

Possibly related: when in the ST-Community-Installer smartapp on the Classic SmartThings app Marketplace in My Apps, it shows the HomeBridge app but when I tap Install, it hangs indefinitely at 'Analyzing Repo'.

**Comment by MCT80** [comment]
Also having this error when trying to install the repo in smartthings
You don't have access to tonesto7/homebridge-smartthings-v2

**Comment by jonpeng** [comment]
Same issues:
You don't have access to tonesto7/homebridge-smartthings

**Comment by benlake** [comment]
Same:
You don't have access to shackrat/SmartThings-by-Shackrat

**Comment by simonrb2000** [comment]
I'm having the same issue. Did you find a workaround?

**Comment by mikepasco** [comment]
The fix for me was to disconnect from GitHub in the SmartThings IDE and then reconnect. I had GitHub connected for a few years with the older pdlove homebridge integration, maybe the auth gets stale?

**Comment by simonrb2000** [comment]
> The fix for me was to disconnect from GitHub in the SmartThings IDE and then reconnect. I had GitHub connected for a few years with the older pdlove homebridge integration, maybe the auth gets stale?

Thank you however we can’t connect GitHub here in the UK. I’ve tried everything and now out of ideas.
