### ISSUE TITLE
Add SmartSense Moisture with "Water Sensor" Capability

### ISSUE THREAD

**Issue by humac** [tonesto7/homebridge-smartthings#32]
Add SmartSense Moisture Sensor or other flood sensors that use "Water Sensor" Capability.

[SmartThings] Device Added - Group sensor, Name Laundry Room Moisture, ID <ID), JSON: {"name":"Laundry Room Moisture","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Water Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":23,"battery":77,"water":"dry"}}

**Comment by leoneleone** [comment]
I second this request. 
Please add Water Leak (moisture sensor).
Great plugin btw 😊

**Comment by pdlove** [comment]
@leoneleone  Thanks.
Any recommendation on a water sensor? I'm wanting to put one in my hot water heater pans and under the condensor moisture tray on my AC unit.

**Comment by leoneleone** [comment]
@pdlove I've got a couple insteon water leak sensors, and some SmartThings SmartSense water sensors around the house. They all perform well enough. I'm in the UK, smartthings in europe has very little third party device integration at the moment. To be honest Samsung isn't a company I would vouch for...
It depends on your usage model.

I will however be purchasing a ConnectSense HomeKit compatible Water Sensor once it's on the market this spring. From April I believe.
I prefer direct notifications to my iPhone/AppleWatch when it comes to Leak sensors. I'm hoping HomeKit will only improve, and improve fast in the coming year.

**Comment by leoneleone** [comment]
@pdlove
Ok I've just tested a Fibaro leak sensor. If you plan to use the sensors with SmartThings hub, Fibaro is your best bet for water Leak and Motion Sensors. The devices can be configured independently and seem to fill in the gaps that HomeKit has at the moment. I'm using Fibaro motion sensors now and I love them I can set sensitivity and Motion Off command delays. Works really well with HomeKit. There's delay of course because everything has to go through the SmartThings hub, but the lag is very tolerable. 

Hope that helps

**Comment by edasque** [comment]
Same here, with SmartSense Moisture sensor.

**Comment by garywkfung** [comment]
@leoneleone

Can you give an explanation on how to get motion sensors to work with homekit? I've been researching for 2-3 days and I literally cannot find anyone who have successfully done it.

**Comment by pdlove** [comment]
What are you trying to do? I have a rule on HomeKit setup for "if motion then lights" but it was painful. And only seems to work when my phone is unlocked.

**Comment by garywkfung** [comment]
Well can you explain how the setup works? I'd like to know how good it is before making the purchase. 

- Does the motion sensor become an accessory in homebridge? 
- Can you use the motion sensor as triggers in homekit? 
- Can you program the montion sensor to trigger something after a period of inactivity?

**Comment by barquestdan** [comment]
Add my name to the list of people who'd like to see moisture sensing capability to homebridge.
By the way... this plugin is amazing!  Works like a champ!

Great work all!

[1/5/2017, 1:42:09 PM] [SmartThings] Device Skipped - Group unknown, Name Basement Water Sensor, ID ded8512b-144d-427d-9382-bcb754e76b64, JSON: {"name":"Basement Water Sensor","deviceid":"ded8512b-144d-427d-9382-bcb754e76b64","capabilities":{"Battery":1,"Water Sensor":1,"Sensor":1},"commands":{},"attributes":{"battery":null,"water":"dry"}}

**Comment by pdlove** [comment]
Also #131 and #125
