### ISSUE TITLE
[Feature Request] Television support

### ISSUE THREAD

**Issue by radiocolin** [tonesto7/homebridge-smartthings#340]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would love if my Samsung Tizen TV, which is connected to SmartThings, could be translated to Homebridge as a TV.

**Describe alternatives you've considered**
I'm currently using homebridge-tizen, so this would mean one less dependency.

**Comment by tonesto7** [comment]
I'm closing this for now as I have no plans to support this in the future
