### ISSUE TITLE
Cannot Access This Repo - States Don't Have Access & Community Installer Says Not Added

### ISSUE THREAD

**Issue by Wildcat1** [tonesto7/homebridge-smartthings#355]
Per the title, trying to get hold of your great repo in Smarthings but when I try to add as a repo under settings I get 'You don't have access to tonesto7/homebridge-smartthings'

When I use the community installer I it shows the check mark on IDE Authentication then the same on Github Integration but states Not Added.

Trying to figure out why I am seeing these issues. Any assistance is greatly appreciated.

**Comment by tannebil** [comment]
I had the same problem but disconnecting the IDE from my GitHub and reconnecting resolved it.

**Comment by Wildcat1** [comment]
That solved it thanks ! 

> I had the same problem but disconnecting the IDE from my GitHub and reconnecting resolved it.
> […](#)
> Sent from my iPhone
> On Aug 19, 2020, at 3:32 PM, Wildcat1 ***@***.***> wrote: ﻿ Per the title, trying to get hold of your great repo in Smarthings but when I try to add as a repo under settings I get 'You don't have access to tonesto7/homebridge-smartthings' When I use the community installer I it shows the check mark on IDE Authentication then the same on Github Integration but states Not Added. Trying to figure out why I am seeing these issues. Any assistance is greatly appreciated. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
