### ISSUE TITLE
Air conditioner displayed as security alarm?

### ISSUE THREAD

**Issue by bsoener** [tonesto7/homebridge-smartthings#408]
At the Homekit my Samsung air conditioner displayed as security alarm and in addition my air conditioner? Did I miss something? Please help.  
  {
            "platform": "SmartThings-v2",
            "name": "SmartThings-v2",
            "app_url": "https://graph-eu01-euwest1.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "xxxxxxxxxx",
            "access_token": "xxxxxxxxxxxxx",
            "temperature_unit": "C",
            "validateTokenId": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": false,
                "hideNamePrefix": false,
                "file": {
                    "enabled": true
                }
            }

<img width="173" alt="Bildschirmfoto 2021-01-30 um 17 46 06" src="https://user-images.githubusercontent.com/77502899/106362454-2b83df80-6323-11eb-857c-621ecb6f1ff0.png">

**Comment by juliangorge** [comment]
Did you fix this?

**Comment by bsoener** [comment]
No..

**Comment by mjolknasbacken** [comment]
Same issue for me

**Comment by bsoener** [comment]
Does anyone have a solution for this?

**Comment by lrcg-test** [comment]
same problem here

**Comment by juliangorge** [comment]
> Turn off SHM in the homebridge app in smart apps SmartThings, that security alarm will go away

Where is it, bro?
