### ISSUE TITLE
SmartThings Outlet (Zigbee) Shows as Two On/Off Switches

### ISSUE THREAD

**Issue by humac** [tonesto7/homebridge-smartthings#51]
So this device reports as 2 duplicate power (on/off) devices and a power consumption device in homekit.

Of the duplicated on/off switches only one of them works and the other seems to do nothing.

**Comment by kenthua** [comment]
I see the same, two on/off switches for each device, with the Aeon Z-Wave Smart Energy Switch (DSC06106-ZWUS)

**Comment by ajvwhite** [comment]
Have the same issue here too, outlets turn up as two separate devices

**Comment by yeungones** [comment]
Similar problem with the Samsung Smartthings outlet.
As shown in the Eve app, I appear to have 3 outlet switches (2 of which don't work so i've hidden them). 
When configuring the SmartApps (in the JSON Complete API), I have added the Outlet under "Most Devices". But have also tried this under "All Switches" with the exact same issue?
I'm using version 0.4.1 of the JSON Complete API; and 0.4.7 homebridge-smartthings plugin.
Any help with this one?
Cheers

![img_1577](https://cloud.githubusercontent.com/assets/20384684/16714747/e2aae198-46c4-11e6-9085-d0e62b1fe81c.PNG)

**Comment by am80l** [comment]
+1

**Comment by mshollack** [comment]
Same thing  two on/off switches for each device, with the Aeon Z-Wave Smart Energy Switch (DSC06106-ZWUS) and also the micro dimmers. Only one item works and the other does nothing.

**Comment by codingthoughts** [comment]
I have the same issue

**Comment by BrentHeyes** [comment]
I've had the same issue with both a SmartThings Outlet and a Fibaro Dimmer 2 module; duplicate devices appearing within HomeKit, one for the switch (that actually works) and another marked as an outlet, which doesn't appear to do anything.

After looking through the homebridge debug log when both devices are switched on and off via HomeKit, the instructions are being sent to homebridge as different characteristics on the same device.

I also observed that the outlet characteristics appeared to be different for the SmartThings Outlet and the Fibaro Dimmer 2 module:

- The SmartThings Outlet uses the Power Meter characteristic
- The Fibaro Dimmer 2 module uses the Energy Meter characteristic

To hide both outlets from HomeKit (leaving only the switch devices), I stopped the homebridge-smartthings plugin from setting the "Energy Meter" and "Power Meter" characteristics by removing the following block of code from the accessories module:
/usr/local/lib/node_modules/homebridge-smartthings/accessories/smartthings.js
```
if (device.capabilities["Energy Meter"] !== undefined) {
  this.deviceGroup = 'EnergyMeter';
  thisCharacteristic = this.getaddService(Service.Outlet).addCharacteristic(EnergyCharacteristics.TotalConsumption1)
  thisCharacteristic.on('get', function(callback) { callback(null, Math.round(that.device.attributes.energy)); });
  that.platform.addAttributeUsage("energy", this.deviceid, thisCharacteristic);
}

if (device.capabilities["Power Meter"] !== undefined) {
  thisCharacteristic = this.getaddService(Service.Outlet).addCharacteristic(EnergyCharacteristics.CurrentConsumption1)
  thisCharacteristic.on('get', function(callback) { callback(null, Math.round(that.device.attributes.power)); });
  that.platform.addAttributeUsage("power", this.deviceid, thisCharacteristic);
}
```
After I restarted homebridge, the outlet devices disappeared from HomeKit.
