### ISSUE TITLE
Fans Are Only Accessible as Lights

### ISSUE THREAD

**Issue by thoward1234** [tonesto7/homebridge-smartthings#55]
Great work by the way (just to throw that in :+1:).  

I have been seeing an interesting phenomenon (bug) since I started using this.  After looking around, I figure it must in the JSON side.  I have a wide variety of lights, switches and bulbs throughout my house.  I also have three ceiling fans on GE Ceiling Fan Zwave switches.  Everything works fine (using the Eve app) EXCEPT the app will only let me define my ceiling fans as lights.  The dimmable switches in my system can be defined as lights, fans, heater, anything.  Is this a bug?  Or is it in the Eve app?

Thanks

**Comment by pdlove** [comment]
What Device Type is being used for these? There shouldn't be any reason you can't define them in Eve as lights, fans, heater, etc.

**Comment by thoward1234** [comment]
I am using GE 12730 Z-Wave Smart Fan Control.  With ST, it functions like a dimmer.  (0-100%) level.  In practice, it has LOW/MED/HIGH settings.   Any app I use forces dimmers (including fans) to be associated as Light bulbs.  On/Off switches however can be associated as other things...

**Comment by brendanjerwin** [comment]
I'm in the same boat. Another homebridge plugin I used in the past (for Indigo) allowed overriding of some items to appear as switches which let me reassign them in HomeKit as fans. I don't recall if that let me control speed though... I _think_ it was just binary control.

The ability to override the type to fan or switch would help smooth this out I bet. @pdlove would that be a reasonable thing to do? Where does the mapping of SmartThings characteristics to HomeKit happen? I bet an override could be applied per device there.

I'll take a look at making the change. Are there any other use-cases that might be covered by being able to override characteristics mappings?

**Comment by brendanjerwin** [comment]
Ah, more digging around and I see that I should use a user defined device type for the fan control module. (still new to ST, so that wasn't obvious to me.)

Related: #59 and #106

**Comment by pdlove** [comment]
I think it would be a good idea for me to add an override option to override a device as either a light, outlet or fan. I'll take a look and see what I can do. It will likely be by device name but I'll see if I can expose an id to use instead.
