### ISSUE TITLE
Not pulling in current data from Nest

### ISSUE THREAD

**Issue by andyweedman** [tonesto7/homebridge-smartthings#72]
Hi, I have nest manager installed in smartthings.  Additionally I am running homebridge and homebridge-smartthings.  When I change the temperature I can view the correct temp in the smartthings app as well as the device result Json in the Json complete Api smart app.  However when I ask Siri what the current set temp is she gives me the wrong value.  If I stop homebridge and start it again the data refreshes.  I have my polling set to 600 seconds and I've waited over that time.

**Comment by andyweedman** [comment]
I can try and do some investigation myself if I can get a hint on where to start.

**Comment by pdlove** [comment]
I'll get some pointers together to guide you where to look after I get off work tonight.
