### ISSUE TITLE
smartthings plugin install

### ISSUE THREAD

**Issue by bkballer917** [tonesto7/homebridge-smartthings#76]
i tried installing smartthings plugin nad i am getting this msg.

pi@raspberrypi:~ $ sudo npm install -g homebridge-smartthings
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/request/n0.3.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/request/n
npm WARN unmet dependency which is version 0.1.5
homebridge-smartthings@0.4.7 /usr/local/lib/node_modules/homebridge-smartthings

**Comment by Abdulrahman79** [comment]
npm install -g homebridge-smartthings
npm ERR! tar.unpack untar error /Users/iman/.npm/homebridge-smartthings/0.4.7/package.tgz
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-smartthings"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path /usr/local/lib/node_modules/homebridge-smartthings
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-smartthings'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-smartthings']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/homebridge-smartthings',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/homebridge-smartthings',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/iman/npm-debug.log

**Comment by pdlove** [comment]
@abdulrahman79 it looks like you aren't sudo-ing the command.

**Comment by Abdulrahman79** [comment]
@pdlove  Don't now how can you explain ?

**Comment by Jessassin** [comment]
@Abdulrahman79 `sudo npm install -g homebridge-smartthings --unsafe-perm`

**Comment by pdlove** [comment]
@Abdulrahman79 Did you ever get running?
