### ISSUE TITLE
Will this work with Go Control/Linear Garage door opener thats connected to smart things?

### ISSUE THREAD

**Issue by samtarr** [tonesto7/homebridge-smartthings#96]
I'm trying to figure out what garage door opener to purchase. The only one thats compatible for me looks like the go control/ linear opener. Does anyone know if I'll be able to use home kit to open the garage doors through home bridge? Thanks

**Comment by erickpece** [comment]
Yes you can.  I have this one: https://www.amazon.com/gp/product/B00M75TEIU and I just set it up with Homebridge this evening.  I'm able to see the current state of the door, as well as control it using Siri or by tapping it.

Here's what it looks like in Control Center:

![screen shot 2016-09-30 at 12 29 06 am](https://cloud.githubusercontent.com/assets/8796466/18980708/f54c3b24-86a4-11e6-9abc-7b3c34912bc8.png)

**Comment by samtarr** [comment]
Just hooked mine up and it also works. IF I have an automation for it to close at a certain time it gets confused and thinks it opening it if its already closed. It doesn't actually open, but home kit will says its opening until it actually does open and then it fixes itself.

**Comment by travismmorgan** [comment]
For me, the garage door switch and sensor show up separately and the switch gets stuck in the 'Closing...' state until it is opened again. Anyone find a solution?

**Comment by kpdillon** [comment]
This is not a proper fix but I have the same problem with garage stuck in "closing".  This is what I am doing to get around it:

148                     case 'closed':
149                         callback(null, Characteristic.TargetDoorState.CLOSED);
150                         break;
151                     case 'closing': <-------------- changed this word from closing to closed.
152                         callback(null, Characteristic.TargetDoorState.CLOSED);

**Comment by crizzwald** [comment]
@erickpece What hub do you have this configured too, Samsung SmartThings Hub?

**Comment by vivekmreddy** [comment]
kpdillon, where is this code that you're changing?

**Comment by kpdillon** [comment]
I modified the code here: /usr/local/lib/node_modules/homebridge-smartthings/accessories/smartthings.js

**Comment by frakman1** [comment]
@erickpece What homebridge plugin should I get to just add the GoControl/Linear controller. I don't want to get the Smartthings plugin and add everything that's on Smartthings because I already have some items on HomeKit natively and didn't want duplicates.
