### ISSUE TITLE
Samsung Multipurpose Sensor not working properly

### ISSUE THREAD

**Issue by hquinones** [tonesto7/homebridge-smartthings#97]
Sensors have been added in JSON Complete API app and devices are added successfully when home bridge starts. They show up on the homekit app as sensors but do not update properly when doors are opened or closed.  Non Samsung door sensors are working properly.  Only my Samsung Multipurpose  sensors are not working

**Comment by xtech86** [comment]
I've got all my switches and my sonos connected perfectly. But none of my sensors are working either. Mine are not even being picked up. 

In the UK.

**Comment by 5t1tch** [comment]
My smartthings motion sensors work perfectly but the multi sensor is more often than not showing incorrect status open/closed . It stays saying open even tho it's closed until I go and reopen and close it a few times , any help?

**Comment by DanielGalle** [comment]
Same here. Temperature and Battery Status shows up correctly but the status (open/close) is never updated?? Motion Sensor is not working either :(

**Comment by DanielGalle** [comment]
And me again - had a look for other problems and found an older issue...

There is one row missing in the code of smartthings.js (the post was from February - why wasn't it implemented yet??)

Here is the link: https://github.com/pdlove/homebridge-smartthings/commit/23e137b294a1200f4557eeb62e982c934bc4080e

**Comment by rknabe** [comment]
Same here on Samsung multi purpose sensor. Seems to be when open and close Happens close together.

**Comment by dcon7776** [comment]
I am having the same issue as well. Homekit can display the temp reading and battery  level, but not the open or close state. I tried re-configuring the sensor's device category on the JSON config from "Most Devices," "Sensor Devices," to "All switches" grouping but nothing helped. My thought was that by selecting the proper device category would add an additional functionality to the device like from a regular on/off switch to on/off + another state switch. But it seems like the device grouping is just for grouping. Any idea on how to fix this problem?

**Comment by SqueakyFox1001** [comment]
I am having the same problem as all the other posters. My SmartThings Multipurpose sensors only work for reporting temperature. I cannot get it to work as an open/close sensor nor to detect motion when it is moved.

**Comment by edifyyo** [comment]
I, too, am having a very similar (same?) problem - via HomeBridge, all four of my SmartThings Multipurpose Sensors report the current temperature; two of the four report battery percentage (the other two report "0%" even though they have new batteries); and none of them report changes in open/close status.
